### ISSUE TITLE
load returns null when passing $select

### ISSUE THREAD

**Issue by ericuldall** [feathersjs-ecosystem/dataloader#7]
When composing a .load call as follows it returns null:
```
loader.service('service').load(id, { query: { $select: ['name', 'path'] } });
```

If I run the same load without the $select it works fine.

**Comment by DaddyWarbucks** [comment]
Be sure to include the `id` in the `$select`. I believe the code should do that anyway, but it can't batch things if there is no `id` to key off of.

**Comment by ericuldall** [comment]
That makes too much sense. Will try today :)

**Comment by ericuldall** [comment]
Looks like that works!

Wondering if it makes sense to account for that in the batch loader. 
Add the _id to any selects that are missing it, then strip it from the results where necessary... in my use case it's not a big deal that it's there but if someone were trying to obscure the _id for any reason it could be a problem.

**Comment by DaddyWarbucks** [comment]
There are some Feathers DB adapters that always require the `id` (and handle stubbing it into $select like you have suggested). This is done mainly for patch/update methods where there is a query involved that the updated data may change. For example
```js
app.service('things').patch(null, { age: 40 }, { query: { $age: { 30 } } })
```
Many ORM's patch methods don't return results. So the patch (and some other methods) do some additional lookups using the IDs. You mentioned `_id` so I am guessing you are using Mongo, which the Mongo adapters is one that does this if I remember correctly. 
With that said, this library should definitely ensure `id` is selected so that it "just works" (which was the main design goal compared to using vanilla dataloader). But I would be reluctant to then pluck them off for performance reasons and because it is somewhat expected with some adapters.

**Comment by ericuldall** [comment]
Makes sense, could always be squelched in an after hook if the end user really cares.
